export default {
  fire: jest.fn(),
  mixin: jest.fn(() => ({ fire: jest.fn() })),
  close: jest.fn(),
  update: jest.fn(),
  isVisible: jest.fn(),
  getPopup: jest.fn(),
  getTitle: jest.fn(),
  getContent: jest.fn(),
  getActions: jest.fn(),
  getConfirmButton: jest.fn(),
  getCancelButton: jest.fn(),
  getFooter: jest.fn(),
  showLoading: jest.fn(),
  hideLoading: jest.fn(),
  getTimerLeft: jest.fn(),
  stopTimer: jest.fn(),
  resumeTimer: jest.fn(),
  toggleTimer: jest.fn(),
  isTimerRunning: jest.fn(),
  increaseTimer: jest.fn(),
  queue: jest.fn(),
  getQueueStep: jest.fn(),
  insertQueueStep: jest.fn(),
  deleteQueueStep: jest.fn(),
  showValidationMessage: jest.fn(),
  resetValidationMessage: jest.fn(),
  getInput: jest.fn(),
  disableInput: jest.fn(),
  enableInput: jest.fn(),
};
